# Site settings
title: Ruby Everyday
email: douglas.rossignolli@gmail.com
description: "Playing with ruby everyday, learning about ruby, rails, rspec, js, css, tdd, bdd. Getting connected with whats happening on ruby and rails comunity."
baseurl: ""
url: "http://www.ruby-everyday.ninja"

username: "Douglas Rossignolli"
git: xdougx


# Build settings
markdown: kramdown
permalink: pretty
